"""
Django settings for project2 project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4dd*j3*ony@-dedakx3f9lg1k!y5c9lm@97b)9^s^l@pb#a23z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'leaflet',
    'social_django',
    'usersapp.apps.UsersConfig',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rasterapp',
    'import_export',
    
    # 'usersapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'project2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect', # <--
            ],
        },
    },
]
AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'project2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'backend',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
# SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
IMPORT_EXPORT_USE_TRANSACTIONS = True

STATIC_URL = '/static/'
CRISPY_TEMPLATE_PACK = 'bootstrap3'
SOCIAL_AUTH_POSTGRES_JSONFIELD = True
LOGIN_URL='/login/'
LOGOUT_URL= '/logout'
LOGIN_REDIRECT_URL = '/home/'
# SOCIAL_AUTH_URL_NAMESPACE = "rasterapp:social"
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_GITHUB_KEY = '855264961b704c4c96f1'
SOCIAL_AUTH_GITHUB_SECRET = '0708b1b3eedbf273e1d6cfdb6eccdc388699baf6'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1033223687149-dth6n65r0tum0i55sv1np7batjll64no.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'YSLCPW-SLpQu09ERvLRYs3F8'

# SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get("860938840929486","none")
# SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get("b5c514cac15043a63e366b823a2ce2ad","none")
SOCIAL_AUTH_FACEBOOK_KEY = '362564167662819'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = '55cc35c7c442b3da846ff70f5aef978b' 

SOCIAL_AUTH_TWITTER_KEY = 'pQ4d8qKhq5TOsWYZQlHq6k2Wg'  # App ID
SOCIAL_AUTH_TWITTER_SECRET = 'NiMj0BxaM33xWD7I38Idq4JVgBWT9IWBEgeZA24HQ21Pw7wEIZ ' 
